# PHẦN 1

In [2]:
!python --version

Python 3.8.19


In [1]:
!pip show numpy

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: c:\users\duyen\anaconda3\envs\py38\lib\site-packages
Requires: 
Required-by: mkl-fft, mkl-random, torchvision


In [2]:
import torch 

In [4]:
x = torch.empty(5,3)
x = torch.rand(5,3)
x

tensor([[0.0106, 0.4023, 0.8352],
        [0.9254, 0.8809, 0.3500],
        [0.7632, 0.6264, 0.9680],
        [0.4394, 0.5836, 0.5131],
        [0.7816, 0.3730, 0.6863]])

In [7]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [3]:
x = torch.Tensor(5,3)
x = torch.Tensor([5.5 , 3.3])
x

tensor([5.5000, 3.3000])

In [5]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# Cùng kích thước, chỉnh sửa kiểu dữ liệu
y = torch.randn_like(x, dtype=torch.double)
y

tensor([[-0.0923, -0.0178, -1.1676],
        [ 1.4258, -1.0945,  1.7633],
        [-0.8036,  0.6655,  0.1622],
        [-0.3989, -0.3759, -0.7748],
        [-0.2473,  0.6556,  0.4526]], dtype=torch.float64)

In [8]:
# y.shape
y.size()

torch.Size([5, 3])

In [13]:
z = x+y
z = torch.add(x,y)
y.add_(x)
torch.add(x,y, out=z)
y


tensor([[2.9077, 2.9822, 1.8324],
        [4.4258, 1.9055, 4.7633],
        [2.1964, 3.6655, 3.1622],
        [2.6011, 2.6241, 2.2252],
        [2.7527, 3.6556, 3.4526]], dtype=torch.float64)

In [14]:
a = torch.rand(4,4)
a

tensor([[0.9572, 0.5511, 0.3033, 0.0941],
        [0.5517, 0.3879, 0.2400, 0.3042],
        [0.5154, 0.8168, 0.8673, 0.4864],
        [0.4663, 0.5343, 0.4953, 0.8523]])

In [16]:
a[0:2,1]

tensor([0.5511, 0.3879])

In [19]:
y = a.view(16)
print(y)
y.shape

tensor([0.9572, 0.5511, 0.3033, 0.0941, 0.5517, 0.3879, 0.2400, 0.3042, 0.5154,
        0.8168, 0.8673, 0.4864, 0.4663, 0.5343, 0.4953, 0.8523])


torch.Size([16])

In [23]:
# cách đổi kích thước của mảng
y = a.view(-1,8)    # -1 để tensor tự tính kích thước của hàng
y


tensor([[0.9572, 0.5511, 0.3033, 0.0941, 0.5517, 0.3879, 0.2400, 0.3042],
        [0.5154, 0.8168, 0.8673, 0.4864, 0.4663, 0.5343, 0.4953, 0.8523]])

In [24]:
x = torch.randn(1)
x

tensor([0.0465])

In [25]:
x.item()

0.046530961990356445

In [26]:
x = torch.rand(3,3)
x

tensor([[0.8663, 0.0216, 0.1606],
        [0.7212, 0.4525, 0.7582],
        [0.4960, 0.0930, 0.3853]])

In [30]:
y = x.numpy()
y

array([[0.8662573 , 0.02163428, 0.16057265],
       [0.721211  , 0.45250183, 0.75815153],
       [0.49601072, 0.09299207, 0.3852573 ]], dtype=float32)

In [ ]:
# tensor -> array: .numpy()
# array --> tensor: torch.from_numpy(array)

In [32]:
x

tensor([[0.8663, 0.0216, 0.1606],
        [0.7212, 0.4525, 0.7582],
        [0.4960, 0.0930, 0.3853]])

In [31]:
# Nhận biết GPU CPU
device = torch.cuda.is_available()
device

True

In [36]:
if device:
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)

tensor([[1.8663, 1.0216, 1.1606],
        [1.7212, 1.4525, 1.7582],
        [1.4960, 1.0930, 1.3853]], device='cuda:0')


# PHẦN 2: 
torch.Tensor()  
.requires_grad: có lưu thông tin của gradient không?  
.grad: lưu thông tin hàm số  
.grad_fn: Lưu thông tin hàm số đã được sử dụng    
.backward(): Phương thức tính toán backward  

In [ ]:
import torch

In [38]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [39]:
y = torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [40]:
y.backward()

In [41]:
x.grad    # lấy đạo hàm 

tensor(7.3891)